version: '2'
services:
  web_wallet:
    build: ./wallet
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./data/wallet:/data/wallet/data
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
